### PR TITLE
add **kwargs for keyword argument to be passed to `plotting.plot_image`

### PR DESCRIPTION
**Pull request by silvbarb**

### CODE REVIEW

**Review by csoneson — COMMENTED** [review]
Just my 2 cents: this works well e.g. to specify `call_show` as in the test, but I think it could potentially be problematic (or at least mildly confusing 🙂) if a user specifies an argument that is already created inside `plot_well()` and sent to `plot_image()`. For example, if I add `im` (which is a valid argument of `plot_image()`, but not of `plot_well()`, so it might seem like a good candidate), I get 
```
TypeError: ez_zarr.plotting.plot_image() got multiple values for keyword argument 'im'
```
It may not be totally obvious which of the arguments will work. Perhaps it would be useful to check if one of these 'problematic' arguments is provided by the user, and in that case either ignore it or raise an error? (Or to copy the useful arguments explicitly to `plot_well()`).

**Comment by silvbarb** [comment]
Yes, I see your point, thanks for spotting this! 

Even if in some cases we have avoided **kwargs, and explicitly exposed the arguments that can be internally passed (e.g. `pyramid_level_coord` added to `plot_well`, to be passed to `get_image_ROI` and `get_label_ROI`), this option makes the argument list of the outer function very long, and potentially more confusing to the user.

Which approach would you suggest? How about we filter the allowed **kwargs in the outer function? 
Something like: 
```
def outer_function(arg1, arg2, **kwargs):
    allowed_kwargs = {"allowed_arg1", "allowed_arg2"}
    filtered_kwargs = {k: v for k, v in kwargs.items() if k in allowed_kwargs}

    inner_function(arg1, arg2, **filtered_kwargs) 
```
in this way we can throw out `im` and keep `call_show`, but in the future we can add other arguments to the allowed ones if needed.

**Comment by csoneson** [comment]
Yes, I think that would work - I'm not sure if it's easier to specify the allowed ones or the forbidden ones (the latter would be the ones that are generated inside the outer function, and one could perhaps imagine initializing a list in the beginning of the outer function and adding to it whenever defining an argument). I think it would be helpful to also alert the user of which of their provided arguments were in fact not passed on (and why).

**Comment by mbstadler** [comment]
Thanks to both for the useful discussion. As decided together, we'll for the moment expose `call_show` from `plot_image` in `plot_well` and close this PR

**Pull request closed without merging**
